env:
  browser: true
  es2021: true
  node: true
extends:
  - '@remix-run/eslint-config'
  - '@remix-run/eslint-config/node'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }]
  'react/jsx-uses-react': 'off'
  'react/react-in-jsx-scope': 'off'
  '@typescript-eslint/quotes': ['warn', 'single', { avoidEscape: true, allowTemplateLiterals: true }]
settings:
  react:
    version: "detect"
